/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.woo.main;

import com.jobits.woo.domain.Client;
import com.jobits.woo.domain.Orden;
import com.jobits.woo.module.WooCoreModule;
import com.jobits.woo.sales.WooSalesApi;
import com.jobits.woo.sales.impl.WooSalesApiImpl;
import java.io.FileNotFoundException;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;
import java.util.function.IntFunction;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Action;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.text.DefaultEditorKit;

/**
 *
 * @author Jorge
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    private WooSalesApi api = new WooSalesApiImpl();

    private DefaultListModel<Orden> listModel = new DefaultListModel<>();

    private Action[] textActions = {new DefaultEditorKit.CutAction(),
        new DefaultEditorKit.CopyAction(), new DefaultEditorKit.PasteAction()};

    public App() {
        initComponents();
        jList1.setModel(listModel);
        jButtonCargarDatos.addActionListener((e) -> {
            cargarDatos();
        });
        jButtonMarcarCompletado.addActionListener((e) -> {
            marcarCompletados();
        });
        jButton1.addActionListener((e) -> {
            jTextArea1.paste();
        });
    }

    private void cargarDatos() {
        listModel.clear();
        listModel.addAll(api.getOrdenesActivas());
    }

    private void marcarCompletados() {
        List<Integer> ints = new ArrayList<>();
        if (jTextArea1.getLineCount() > 1) {
            for (String line : jTextArea1.getText().split("\\n")) {
                ints.add(Integer.parseInt(line));
            }
            Integer[] ret = new Integer[ints.size()];
            api.completeOrden(ints.toArray(ret));
            cargarDatos();
            jTextArea1.setText("");
        } else {
            api.completeOrden(jList1.getSelectedValuesList());
            cargarDatos();

        }
    }

    private void printCustomersPhones() {
        PrintStream out = null;
        try {
            out = new PrintStream("clients.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
//        for (Client c : api.getClients()) {
//            if (out != null) {
//                out.printf("%s;%s;%s;%s;%s;%s;%s;%s\n",
//                        c.getId(),
//                        !c.getFirst_name().isBlank() ? c.getFirst_name() : c.getBilling().getFirst_name(),
//                        !c.getLast_name().isBlank() ? c.getLast_name() : c.getBilling().getLast_name(),
//                        c.getEmail(),
//                        c.getBilling().getAddress_1(),
//                        c.getBilling().getCity(),
//                        c.getBilling().getCountry(),
//                        c.getBilling().getPhone());
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButtonCargarDatos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonImprimirTodo = new javax.swing.JButton();
        jButtonMarcarCompletado = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setLayout(new java.awt.BorderLayout(5, 5));

        jButtonCargarDatos.setText("Cargar Datos");
        jPanel2.add(jButtonCargarDatos, java.awt.BorderLayout.PAGE_START);

        jButtonImprimirTodo.setText("Imprimir");
        jPanel1.add(jButtonImprimirTodo);

        jButtonMarcarCompletado.setText("Marcar Completado");
        jPanel1.add(jButtonMarcarCompletado);

        jPanel2.add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 130));

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Ordenes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jScrollPane1.setViewportView(jList1);

        jPanel4.add(jScrollPane1);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jButton1.setText("Pegar");
        jPanel5.add(jButton1, java.awt.BorderLayout.SOUTH);

        jPanel4.add(jPanel5);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Pedidos", jPanel2);
        jTabbedPane1.addTab("Impresion Programada", jPanel3);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WooCoreModule.init();
                Thread.setDefaultUncaughtExceptionHandler((Thread t, Throwable e) -> {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                });
                new App().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCargarDatos;
    private javax.swing.JButton jButtonImprimirTodo;
    private javax.swing.JButton jButtonMarcarCompletado;
    private javax.swing.JList<Orden> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
